server.port=8080
spring.application.name=API-GATEWAY

# Import configuration from Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Fallback Routes if Config Server unavailable during initial boot
spring.cloud.gateway.routes[0].id=location-service-route
spring.cloud.gateway.routes[0].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/locations/**

spring.cloud.gateway.routes[1].id=ride-service-route
spring.cloud.gateway.routes[1].uri=lb://RIDE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/rides/**

spring.cloud.gateway.routes[2].id=matching-service-route
spring.cloud.gateway.routes[2].uri=lb://MATCHING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/matching/**

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,env,gateway
