server.port=8888
spring.application.name=config-server

# Config Server Native Search Locations
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,env
